# Generated by Django 4.2.4 on 2023-08-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_year', models.CharField(max_length=4)),
                ('car_make', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=60)),
                ('repair_name', models.CharField(max_length=70)),
                ('repair_cost', models.IntegerField(blank=True)),
                ('repair_quote_cost', models.IntegerField(blank=True)),
            ],
        ),
    ]
