# Generated by Django 3.2.18 on 2023-02-21 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autobuddyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=40)),
                ('model_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autobuddyapp.make')),
            ],
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
